language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false
